
export const VIEW_REDIRECT_HOME                 = "VIEW_REDIRECT_HOME";
export const VIEW_REDIRECT_PURSE                = "VIEW_REDIRECT_PURSE";
export const VIEW_REDIRECT_VAULT                = "VIEW_REDIRECT_VAULT";


export const USER_PURSE_ALLOCATION_ADD          = "USER_PURSE_ALLOCATION_ADD";
export const USER_PURSE_ALLOCATION_UNLOCK       = "USER_PURSE_ALLOCATION_UNLOCK";
export const USER_PURSE_ALLOCATION_LOCK         = "USER_PURSE_ALLOCATION_LOCK";
export const USER_PURSE_ALLOCATION_SET_ACTIVE   = "USER_PURSE_ALLOCATION_SET_ACTIVE";
export const USER_PURSE_ALLOCATION_ADD_CASH     = "USER_PURSE_ALLOCATION_ADD_CASH";
export const USER_PURSE_ALLOCATION_DELETE       = "USER_PURSE_ALLOCATION_DELETE";
export const USER_PURSE_ALLOCATION_RELEASE_CASH = "USER_PURSE_ALLOCATION_RELEASE_CASH"

export const USER_SAVINGSACCOUNT_TO_VAULT        = "USER_SAVINGSACCOUNT_TO_VAULT"
export const USER_SAVINGSACCOUNT_FROM_VAULT      = "USER_SAVINGSACCOUNT_FROM_VAULT"

export const USER_VAULT_ALLOCATION_ADD          = "USER_VAULT_ALLOCATION_ADD";
export const USER_VAULT_ALLOCATION_ADD_CASH     = "USER_VAULT_ALLOCATION_ADD_CASH";
export const USER_VAULT_ALLOCATION_DELETE       = "USER_VAULT_ALLOCATION_DELETE";
export const USER_VAULT_ALLOCATION_RELEASE_CASH = "USER_VAULT_ALLOCATION_RELEASE_CASH"


export const TASK_POCKET_ADD_NEW                = "TASK_POCKET_ADD_NEW";
export const TASK_POCKET_ADD_AMOUNT             = "TASK_POCKET_ADD_AMOUNT";
export const TASK_POCKET_RELEASE_AMOUNT         = "TASK_POCKET_RELEASE_AMOUNT";
