
export const VIEW_REDIRECT_HOME                         = "VIEW_REDIRECT_HOME";
export const VIEW_REDIRECT_HOME_RESOLVED                = "VIEW_REDIRECT_HOME_RESOLVED";
export const VIEW_REDIRECT_PURSE                        = "VIEW_REDIRECT_PURSE";
export const VIEW_REDIRECT_VAULT                        = "VIEW_REDIRECT_VAULT";
export const USER_SIGNIN                                = "USER_SIGNIN"


export const USER_PURSE_ALLOCATION_ADD                  = "USER_PURSE_ALLOCATION_ADD";
export const USER_PURSE_ALLOCATION_ADD_RESOLVED         = "USER_PURSE_ALLOCATION_ADD_RESOLVED";
export const USER_PURSE_ALLOCATION_ADD_CASH             = "USER_PURSE_ALLOCATION_ADD_CASH";
export const USER_PURSE_ALLOCATION_ADD_CASH_RESOLVED    = "USER_PURSE_ALLOCATION_ADD_CASH_RESOLVED";
export const USER_PURSE_ALLOCATION_DELETE               = "USER_PURSE_ALLOCATION_DELETE";
export const USER_PURSE_ALLOCATION_DELETE_RESOLVED      = "USER_PURSE_ALLOCATION_DELETE_RESOLVED";
export const USER_PURSE_ALLOCATION_RELEASE_CASH         = "USER_PURSE_ALLOCATION_RELEASE_CASH";
export const USER_PURSE_ALLOCATION_RELEASE_CASH_RESOLVED= "USER_PURSE_ALLOCATION_RELEASE_CASH_RESOLVED"

// export const USER_PURSE_ALLOCATION_UNLOCK               = "USER_PURSE_ALLOCATION_UNLOCK";
// export const USER_PURSE_ALLOCATION_LOCK                 = "USER_PURSE_ALLOCATION_LOCK";
// export const USER_PURSE_ALLOCATION_SET_ACTIVE           = "USER_PURSE_ALLOCATION_SET_ACTIVE";


export const USER_VAULT_ALLOCATION_ADD                  = "USER_VAULT_ALLOCATION_ADD"
export const USER_VAULT_ALLOCATION_ADD_RESOLVED         = "USER_VAULT_ALLOCATION_ADD_RESOLVED"
export const USER_VAULT_ALLOCATION_ADD_CASH             = "USER_VAULT_ALLOCATION_ADD_CASH"
export const USER_VAULT_ALLOCATION_ADD_CASH_RESOLVED    = "USER_VAULT_ALLOCATION_ADD_CASH_RESOLVED"


export const USER_VAULT_ALLOCATION_DELETE               = "USER_VAULT_ALLOCATION_DELETE"
export const USER_VAULT_ALLOCATION_RELEASE_CASH         = "USER_VAULT_ALLOCATION_RELEASE_CASH"

export const USER_SAVINGSACCOUNT_TO_VAULT               = "USER_SAVINGSACCOUNT_TO_VAULT"
export const USER_SAVINGSACCOUNT_TO_VAULT_RESOLVED      = "USER_SAVINGSACCOUNT_TO_VAULT_RESOLVED"
export const USER_SAVINGSACCOUNT_FROM_VAULT             = "USER_SAVINGSACCOUNT_FROM_VAULT"
export const USER_SAVINGSACCOUNT_FROM_VAULT_RESOLVED    = "USER_SAVINGSACCOUNT_FROM_VAULT_RESEOLVED"

export const TASK_POCKET_ADD_NEW                        = "TASK_POCKET_ADD_NEW"
export const TASK_POCKET_ADD_AMOUNT                     = "TASK_POCKET_ADD_AMOUNT"
export const TASK_POCKET_RELEASE_AMOUNT                 = "TASK_POCKET_RELEASE_AMOUNT"

export const MESSAGE_RESET_DEFAULT                      = "MESSAGE_RESET_DEFAULT"

export const USER_INITIALIZE_ACCOUNT_DETAILS            = "USER_INITIALIZE_ACCOUNT_DETAILS"
export const USER_INITIALIZE_ACCOUNT_DETAILS_RESOLVED   = "USER_INITIALIZE_ACCOUNT_DETAILS_RESOLVED"

export const INBOX_READ_MESSAGE                         = "INBOX_READ_MESSAG"
export const INBOX_CLOSE_MESSAGE                        = "INBOX_CLOSE_MESSAG"