
export const VIEW_REDIRECT_HOME                 = "VIEW_REDIRECT_HOME";
export const VIEW_REDIRECT_PURSE                = "VIEW_REDIRECT_PURSE";
export const VIEW_REDIRECT_VAULT                = "VIEW_REDIRECT_VAULT";

export const USER_PURSE_ALLOCATION_ADD          = "USER_PURSE_ALLOCATION_ADD";
export const USER_PURSE_ALLOCATION_UNLOCK       = "USER_PURSE_ALLOCATION_UNLOCK";
export const USER_PURSE_ALLOCATION_LOCK         = "USER_PURSE_ALLOCATION_LOCK";
export const USER_PURSE_ALLOCATION_SET_ACTIVE         = "USER_PURSE_ALLOCATION_SET_ACTIVE";
export const USER_PURSE_ALLOCATION_ADD_CASH     = "USER_PURSE_ALLOCATION_ADD_CASH";
export const USER_PURSE_ALLOCATION_DELETE       = "USER_PURSE_ALLOCATION_DELETE";